import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Card, Pill, SectionTitle } from '../components/UI';
import { DashboardData, UserRole } from '../types';
import { theme } from '../theme';

export function StudentsScreen({ data }: { data: DashboardData }) {
  return <View><SectionTitle title="Öğrenciler" action="+ Öğrenci ekle" /><Card>{data.students.map((s, i) => <View key={s.id} style={[styles.row, i > 0 && styles.border]}><View style={styles.avatar}><Text style={styles.avatarText}>{s.full_name.charAt(0)}</Text></View><View style={{ flex: 1 }}><Text style={styles.title}>{s.full_name}</Text><Text style={styles.meta}>{s.grade_level ?? '—'} · {s.school ?? '—'}</Text></View><Pill tone={s.active ? 'success' : 'neutral'}>{s.active ? 'Aktif' : 'Pasif'}</Pill></View>)}</Card></View>;
}

export function CalendarScreen({ data }: { data: DashboardData }) {
  const sorted = [...data.lessons].sort((a, b) => +new Date(a.starts_at) - +new Date(b.starts_at));
  return <View><SectionTitle title="Ders takvimi" /><Card>{sorted.length ? sorted.map((l, i) => <View key={l.id} style={[styles.row, i > 0 && styles.border]}><View style={styles.dateBox}><Text style={styles.dateDay}>{new Date(l.starts_at).getDate()}</Text><Text style={styles.dateMon}>{new Date(l.starts_at).toLocaleDateString('tr-TR', { month: 'short' })}</Text></View><View style={{ flex: 1 }}><Text style={styles.title}>{l.student_name} · {l.subject_name}</Text><Text style={styles.meta}>{new Date(l.starts_at).toLocaleString('tr-TR', { weekday: 'long', hour: '2-digit', minute: '2-digit' })}</Text><Text style={styles.meta}>{l.topic ?? 'Konu girilmedi'}</Text></View><Pill tone={l.status === 'completed' ? 'success' : l.status === 'cancelled' ? 'danger' : 'primary'}>{l.status === 'completed' ? 'Tamamlandı' : l.status === 'cancelled' ? 'İptal' : 'Planlandı'}</Pill></View>) : <Text style={styles.empty}>Ders kaydı yok.</Text>}</Card></View>;
}

export function HomeworkScreen({ data, role }: { data: DashboardData; role: UserRole }) {
  return <View><SectionTitle title="Ödevler" action={role === 'teacher' ? '+ Ödev ver' : undefined} /><Card>{data.homework.length ? data.homework.map((h, i) => <View key={h.id} style={[styles.row, i > 0 && styles.border]}><View style={styles.check}><Text style={{ fontWeight: '900', color: theme.colors.primary }}>{h.status === 'reviewed' ? '✓' : '•'}</Text></View><View style={{ flex: 1 }}><Text style={styles.title}>{h.title}</Text><Text style={styles.meta}>{role === 'teacher' ? `${h.student_name} · ` : ''}{h.subject_name}</Text><Text style={styles.meta}>Son tarih: {new Date(h.due_at).toLocaleDateString('tr-TR')}</Text></View><Pill tone={h.status === 'reviewed' ? 'success' : h.status === 'submitted' ? 'warning' : 'primary'}>{h.status === 'reviewed' ? 'Tamam' : h.status === 'submitted' ? 'Gönderildi' : 'Bekliyor'}</Pill></View>) : <Text style={styles.empty}>Ödev kaydı yok.</Text>}</Card></View>;
}

export function ProfileScreen({ role, isDemo, onLogout, onSwitchDemoRole }: { role: UserRole; isDemo: boolean; onLogout: () => void; onSwitchDemoRole?: (role: UserRole) => void }) {
  return <View><SectionTitle title="Hesap ve ayarlar" /><Card><View style={styles.profileHeader}><View style={styles.profileAvatar}><Text style={styles.profileLetter}>{role === 'teacher' ? 'Ö' : role === 'parent' ? 'V' : 'A'}</Text></View><View><Text style={styles.title}>{role === 'teacher' ? 'Öğretmen hesabı' : role === 'parent' ? 'Veli hesabı' : 'Öğrenci hesabı'}</Text><Text style={styles.meta}>{isDemo ? 'Demo mod · Supabase bağlı değil' : 'Supabase hesabı'}</Text></View></View>{isDemo ? <View style={styles.demoBox}><Text style={styles.demoTitle}>Rolleri önizle</Text><View style={styles.roleRow}>{(['teacher','parent','student'] as UserRole[]).map(r => <Pressable key={r} onPress={() => onSwitchDemoRole?.(r)} style={[styles.roleButton, role === r && styles.roleButtonActive]}><Text style={[styles.roleButtonText, role === r && styles.roleButtonTextActive]}>{r === 'teacher' ? 'Öğretmen' : r === 'parent' ? 'Veli' : 'Öğrenci'}</Text></Pressable>)}</View></View> : null}<Pressable style={styles.logoutButton} onPress={onLogout}><Text style={styles.logoutText}>{isDemo ? 'Demo başlangıcına dön' : 'Çıkış yap'}</Text></Pressable></Card></View>;
}

const styles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12 }, border: { borderTopWidth: 1, borderTopColor: theme.colors.border }, avatar: { width: 42, height: 42, borderRadius: 13, backgroundColor: '#EEF0FF', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: theme.colors.primary, fontWeight: '900' }, title: { color: theme.colors.text, fontWeight: '900', fontSize: 13 }, meta: { color: theme.colors.textMuted, marginTop: 4, fontSize: 10.5 }, dateBox: { width: 46, height: 50, borderRadius: 13, backgroundColor: '#242946', alignItems: 'center', justifyContent: 'center' }, dateDay: { color: 'white', fontWeight: '900', fontSize: 17 }, dateMon: { color: '#BFC5DA', fontSize: 9, fontWeight: '800', textTransform: 'uppercase' }, check: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#EEF0FF', alignItems: 'center', justifyContent: 'center' }, empty: { color: theme.colors.textMuted },
  profileHeader: { flexDirection: 'row', gap: 14, alignItems: 'center' }, profileAvatar: { width: 54, height: 54, borderRadius: 17, backgroundColor: theme.colors.primary, justifyContent: 'center', alignItems: 'center' }, profileLetter: { color: 'white', fontWeight: '900', fontSize: 20 }, demoBox: { marginTop: 22, paddingTop: 18, borderTopWidth: 1, borderTopColor: theme.colors.border }, demoTitle: { fontWeight: '900', color: theme.colors.text, marginBottom: 10 }, roleRow: { flexDirection: 'row', gap: 8 }, roleButton: { flex: 1, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 12, paddingVertical: 11, alignItems: 'center' }, roleButtonActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary }, roleButtonText: { color: theme.colors.textMuted, fontWeight: '800', fontSize: 11 }, roleButtonTextActive: { color: 'white' }, logoutButton: { marginTop: 20, borderWidth: 1, borderColor: '#F2C7CD', backgroundColor: '#FFF6F7', padding: 14, borderRadius: 14, alignItems: 'center' }, logoutText: { color: theme.colors.danger, fontWeight: '900' },
});
