import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { DashboardData, Profile } from '../types';
import { sendMessage } from '../services/appData';
import { theme } from '../theme';

export function MessageCenter({visible,profile,data,onClose,onChanged}:{visible:boolean;profile:Profile;data:DashboardData;onClose:()=>void;onChanged:()=>Promise<void>|void}){
  const [studentId,setStudentId]=useState(data.students[0]?.id??'');
  const [body,setBody]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!data.students.some(s=>s.id===studentId))setStudentId(data.students[0]?.id??'')},[data.students,studentId]);
  const messages=useMemo(()=>data.messages.filter(m=>m.student_id===studentId),[data.messages,studentId]);
  const student=data.students.find(s=>s.id===studentId);
  const submit=async()=>{if(!body.trim()||!studentId)return;try{setBusy(true);await sendMessage({studentId,senderId:profile.id,body});setBody('');await onChanged();}catch(e:any){Alert.alert('Mesaj gonderilemedi',e?.message??'Bilinmeyen hata');}finally{setBusy(false)}};
  return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><View style={styles.page}><View style={styles.header}><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>{'<'} </Text></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>ILETISIM</Text><Text style={styles.title}>Mesajlar</Text><Text style={styles.meta}>{student?.full_name??'Ogrenci secilmedi'}</Text></View></View>
    {data.students.length>1?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.studentRow}>{data.students.map(s=><Pressable key={s.id} onPress={()=>setStudentId(s.id)} style={[styles.studentChip,s.id===studentId&&styles.studentChipActive]}><Text style={[styles.studentText,s.id===studentId&&styles.studentTextActive]}>{s.full_name}</Text></Pressable>)}</ScrollView>:null}
    <ScrollView contentContainerStyle={styles.list}>{messages.length?messages.map(m=>{const mine=m.sender_id===profile.id;return <View key={m.id} style={[styles.message,mine?styles.mine:styles.theirs]}><Text style={[styles.body,mine&&styles.mineText]}>{m.body}</Text><Text style={[styles.date,mine&&styles.mineDate]}>{new Date(m.created_at).toLocaleString('tr-TR')}</Text></View>}):<Text style={styles.empty}>Henuz mesaj yok. Ilk mesaji sen gonderebilirsin.</Text>}<View style={{height:12}}/></ScrollView>
    <View style={styles.composer}><TextInput value={body} onChangeText={setBody} placeholder="Ders veya odev hakkinda mesaj yaz..." placeholderTextColor="#9AA1B4" multiline style={styles.input}/><Pressable onPress={submit} disabled={busy||!body.trim()} style={[styles.send,(busy||!body.trim())&&styles.disabled]}><Text style={styles.sendText}>Gonder</Text></Pressable></View>
  </View></Modal>;
}

const styles=StyleSheet.create({page:{flex:1,backgroundColor:theme.colors.background},header:{paddingTop:46,paddingHorizontal:18,paddingBottom:14,flexDirection:'row',gap:12,alignItems:'center',backgroundColor:'white',borderBottomWidth:1,borderBottomColor:theme.colors.border},close:{width:40,height:40,borderRadius:13,backgroundColor:'#F1F3F8',alignItems:'center',justifyContent:'center'},closeText:{fontWeight:'900',fontSize:18,color:theme.colors.text},eyebrow:{fontSize:9,fontWeight:'900',color:theme.colors.primary,letterSpacing:1},title:{fontSize:21,fontWeight:'900',color:theme.colors.text,marginTop:2},meta:{color:theme.colors.textMuted,fontSize:10,marginTop:3},studentRow:{padding:12,gap:8,maxHeight:60},studentChip:{backgroundColor:'white',borderWidth:1,borderColor:theme.colors.border,borderRadius:12,paddingHorizontal:13,paddingVertical:9},studentChipActive:{backgroundColor:theme.colors.primary,borderColor:theme.colors.primary},studentText:{color:theme.colors.textMuted,fontWeight:'800',fontSize:11},studentTextActive:{color:'white'},list:{padding:16,gap:9},message:{maxWidth:'82%',borderRadius:17,padding:12},mine:{alignSelf:'flex-end',backgroundColor:theme.colors.primary,borderBottomRightRadius:5},theirs:{alignSelf:'flex-start',backgroundColor:'white',borderWidth:1,borderColor:theme.colors.border,borderBottomLeftRadius:5},body:{color:theme.colors.text,fontSize:12,lineHeight:18,fontWeight:'600'},mineText:{color:'white'},date:{fontSize:8,color:theme.colors.textMuted,marginTop:6},mineDate:{color:'#E6E7FF'},empty:{color:theme.colors.textMuted,textAlign:'center',marginTop:30},composer:{flexDirection:'row',gap:10,padding:14,paddingBottom:24,backgroundColor:'white',borderTopWidth:1,borderTopColor:theme.colors.border,alignItems:'flex-end'},input:{flex:1,minHeight:48,maxHeight:110,borderWidth:1,borderColor:theme.colors.border,borderRadius:15,paddingHorizontal:13,paddingVertical:11,color:theme.colors.text,textAlignVertical:'top'},send:{backgroundColor:theme.colors.primary,borderRadius:14,paddingHorizontal:16,height:48,alignItems:'center',justifyContent:'center'},sendText:{color:'white',fontWeight:'900'},disabled:{opacity:.45}});
